#! /bin/bash

which composer &> /dev/null;
if [ ! $? -eq 0 ]; then
	echo "To use this installer, please install composer globally";
	exit 1;
fi;


mkdir config;
mkdir layout;
mkdir layout/templates;
mkdir layout/widgets;
mkdir lib;
mkdir public;
mkdir www;

curl "https://raw.github.com/oranj/Roto/master/samples/sample.composer.json" > composer.json;

composer install;

cp vendor/oranj/Roto/samples/sample.index.php index.php
cp vendor/oranj/Roto/samples/sample.htaccess .htaccess
cp vendor/oranj/Roto/samples/sample.config.ini config/config.ini
cp vendor/oranj/Roto/samples/sample.general.php lib/general.php
cp vendor/oranj/Roto/samples/sample.services.php lib/services.php